spring:
  cloud:
    bus:
      trace: 
        enabled: true
      enabled: true
      destination: spring_cloud_config_channel
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          brokers: localhost:9095
          consumer-properties:
            allow:
              auto:
                create:
                  topics: false

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, bus-env, reresh, env, trace
  endpoint:
    info:
      enabled: true
    health:
      enabled: true

logging:
  level:
    ROOT: WARN
    com.example.demo.*: info


notification:
  profile: STAGE
  type: EMAIL
  port: 8090
  userName: Test
